### PR TITLE
1.12.2 rebrand

### PR DESCRIPTION
**Pull request by PseudoDistant**
#5 and most of #9 (also ccbb6b8aba8e955551c60810d7c9cb5c611e6060), but on 1.12.2.

### CODE REVIEW

**Comment by PseudoDistant** [comment]
I realized I didn't do this from a new branch...
I should make a habit of making new branches for these things...
Shouldn't affect anything.

**Comment by PseudoDistant** [comment]
I'm not confident I did this correctly...

**Comment by BoogieMonster1O1** [comment]
that's a lot of conflicts.
please resolve

**Comment by PseudoDistant** [comment]
Oh you commented lole .
Not sure how, pretty much all I did was refactor, update build.gradle and gradle.properties, and fix the style so Gradle didn't complain.

**Comment by PseudoDistant** [comment]
@BoogieMonster1O1 I had no idea what I was doing, as I've never resolved a merge conflict before... But somehow I did it and it works.

**Comment by PseudoDistant** [comment]
@BoogieMonster1O1 ye looks good to me, tell me if there's anything wrong with it.

**Pull request merged**
