### PR TITLE
Begin rebrand towards Legacy Rewoven

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Currently modified
- [x] Maven and dependencies
- [x] Project names
- [x] Mod IDs
- [x] Packages 
- [x] Resource Directories

### CODE REVIEW

**Comment by BoogieMonster1O1** [comment]
Ready for review

**Comment by PseudoDistant** [comment]
This PR is very well-formatted, but I feel the presentation could be much better...
7.25/10

**Review by PseudoDistant — APPROVED** [review]
gg

**Comment by PseudoDistant** [comment]
Gotta fix Gradle being an ass...

**Pull request merged**
