### PR TITLE
Port of command API v2 to 1.12.2

### PR DESCRIPTION
**Pull request by PseudoDistant**
A very creative description detailing what I did.

(I'd prefer if it were looked over before being merged, just in case I borked something.

### CODE REVIEW

**Comment by PseudoDistant** [comment]
Why does Gradle do this?
It builds, but only after it fails the first time.
Gradle pls just exist...

**Comment by PseudoDistant** [comment]
The hell is it on about "1 failing check" the thing builds I built it like six times just to be safe AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by BoogieMonster1O1 — APPROVED** [review]
actions brok
if it works, merge

**Comment by PseudoDistant** [comment]
> actions brok if it works, merge

@BoogieMonster1O1 You sure?

**Comment by PseudoDistant** [comment]
Still not positive just how much of it works, but things can always be fixed later if I did break it.

**Pull request merged**
