### PR TITLE
Port of the API to 1.7.10

### PR DESCRIPTION
**Pull request by PseudoDistant**
**Ported:**
- Base
- Keybinding
- Crash-Report-Info
- Events
- Lifecycle
- Gamerules
- Permissions
- Command API v1
- Networking (Needs testing)
- Command API v2 (Needs testing)
- Resource Loader

**In progress:**
- Rendering (Mostly done, needs ItemRenderer mixin.)

I didded a lot :>

### CODE REVIEW

**Comment by PseudoDistant** [comment]
I just realized the base was set to 1.8...
Welp, time to fix some conflicts.

**Comment by PseudoDistant** [comment]
There, I fix.

**Comment by PseudoDistant** [comment]
Not that much else to do without the registry. :/

**Comment by PseudoDistant** [comment]
I'm go sleep now. Make sure it's actually decent before merging.
Tell me if something's wrong.

**Review by BoogieMonster1O1 — APPROVED** [review]

**Pull request merged**
